### ISSUE TITLE
Setting the Kanaban

### ISSUE THREAD

**Issue by PowerLevel9000** [PowerLevel9000/react-group-project#44]
# Kanaban Set up for 2 memeber Group

Kanaban board Link : https://github.com/PowerLevel9000/react-group-project/projects/1

- [ ] assign respective group and individual tasks
- [ ] automatically generated issue

## problems 
- we had an error on terminal 
- so we run it twice 
- so we have a lot of issues with our project 
- we will close duplicate in meantime of our progress

## happy coding 

![CyberFrogsDanceMovesCyberMusicDanceMovesGIF](https://user-images.githubusercontent.com/116451144/224720513-51fc9c41-40e8-4a33-8c23-d6b511ba3d6a.gif)

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @PowerLevel9000 and @Habtamu210,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly provide the link to the Kanban board itself.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @Habtamu210 and @PowerLevel9000 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PowerLevel9000** [comment]
hi @TedLivist @emmanuellekamwa  thanks for your precious reviews
